name: fr
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.7.1
  - pytorch=1.1.0
  - torchvision=0.2.1
  - dlib=19.19
  - imutils=0.5.2
  - opencv=3.4.2
  - joblib=0.14.1
  - numpy=1.15.4
  - scikit-learn=0.22.1
